# Generated by Django 2.0.4 on 2018-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetail',
            fields=[
                ('country', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('capital', models.CharField(max_length=150)),
            ],
        ),
    ]
